import streamlit as st
from health_crew.workflows import build_diagnosis_crew
from health_crew.config import OPENAI_MODEL

st.set_page_config(page_title="Healthcare Diagnosis Support", layout="centered")
st.title("Healthcare Diagnosis Support (CrewAI)")

with st.sidebar:
    st.header("Settings")
    verbose = st.checkbox("Verbose mode", value=True)
    st.caption(f"Model: {OPENAI_MODEL}")

with st.form("patient_input"):
    symptoms = st.text_area("Primary symptoms", placeholder="e.g., fever, cough, fatigue", height=100)
    demographics = st.text_input("Demographics", placeholder="e.g., age 45, male")
    history = st.text_area("Brief medical history", height=120)
    medications = st.text_input("Current medications (comma-separated)")
    allergies = st.text_input("Allergies (comma-separated, leave blank if none)")
    submitted = st.form_submit_button("Run Diagnosis")

if submitted:
    inputs = {
        "symptoms": symptoms or "",
        "demographics": demographics or "",
        "history": history or "",
        "medications": medications or "",
        "allergies": allergies or "",
        "working_differential": "To be generated by Symptom Analyzer",
        "diagnosis_summary": "To be generated by previous steps",
        "proposed_medications": medications or "",
        "conditions": "From differential/diagnosis",
        "treatment_plan": "To be generated by Treatment Agent",
        "referral_plan": "To be generated by Referral Agent",
        "clinical_summary": "Consolidated output",
    }

    try:
        with st.spinner("Running diagnosis crew..."):
            crew = build_diagnosis_crew(verbose=verbose)
            result = crew.kickoff(inputs=inputs)
        st.success("Completed")
        st.subheader("Crew Result")
        if isinstance(result, dict):
            st.json(result)
        else:
            st.write(result)
    except Exception as e:
        st.error(f"Failed to run diagnosis: {e}")
